{
 "title": "OSS大盘",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appId",
    "label": "appId",
    "query": "label_values(aliyun_oss_putobject_counter, appId)"
   },
   {
    "name": "rtCode",
    "label": "rtCode",
    "query": "label_values(aliyun_oss_putobject_counter, rtCode)"
   },
   {
    "name": "remoteCallerIP",
    "label": "remoteCallerIP",
    "query": "label_values(aliyun_oss_putobject_counter, remoteCallerIP)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(aliyun_oss_putobject_counter, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "oss bucket上传次数统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "oss-bucket 上传总次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aliyun_oss_putobject_counter{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"$rtCode\", instance=~\"$instance\"})",
       "legendFormat": "totalCount"
      }
     ]
    },
    {
     "title": "oss bucket上传频度",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(aliyun_oss_putobject_counter{appId=~\"$appId\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"$rtCode\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "上传频度"
      }
     ]
    },
    {
     "title": "oss bucket上传文件失败总次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (rtCode)(aliyun_oss_putobject_counter{appId=\"cdn-release-web-server\", rtCode!=\"CODE_OSS_PUTOBJECT_SUCCESS\"})"
      }
     ]
    },
    {
     "title": "oss bucket上传文件失败频度",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (rtCode)(rate(aliyun_oss_putobject_counter{appId=\"cdn-release-web-server\", rtCode!=\"CODE_OSS_PUTOBJECT_SUCCESS\"}[1m]))"
      }
     ]
    }
   ]
  },
  { "title": "oss bucket上传文件大小统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "上传文件大小总览：cdn-release-web-server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, le) (rate(aliyun_oss_putobject_file_size_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p99-filesize"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(appId, le) (rate(aliyun_oss_putobject_file_size_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p90-filesize"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(appId, le) (rate(aliyun_oss_putobject_file_size_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p50-filesize"
    }
   ]
  },
  {
   "title": "调用者上传文件大小：P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, remoteCallerIP, le) (rate(aliyun_oss_putobject_file_size_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p99-remoteCallerIP：{{remoteCallerIP}}"
    }
   ]
  },
  {
   "title": "调用者上传文件大小：P90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(appId, remoteCallerIP, le) (rate(aliyun_oss_putobject_file_size_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p99-remoteCallerIP：{{remoteCallerIP}}"
    }
   ]
  },
  {
   "title": "调用者上传文件大小：P50",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(appId, remoteCallerIP, le) (rate(aliyun_oss_putobject_file_size_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p50-remoteCallerIP：{{remoteCallerIP}}"
    }
   ]
  },
  { "title": "oss bucket上传文件时间统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "上传文件时间总览：cdn-release-web-server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, le) (rate(aliyun_oss_putobject_time_cost_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p99-timecost"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(appId, le) (rate(aliyun_oss_putobject_time_cost_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p90-timecost"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(appId, le) (rate(aliyun_oss_putobject_time_cost_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p50-timecost"
    }
   ]
  },
  {
   "title": "调用者上传文件耗费时间：P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, remoteCallerIP, le) (rate(aliyun_oss_putobject_time_cost_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "p99-remoteCallerIP：{{remoteCallerIP}}"
    }
   ]
  },
  {
   "title": "调用者上传文件耗费时间：P90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(appId, remoteCallerIP, le) (rate(aliyun_oss_putobject_time_cost_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "调用者上传文件耗费时间：P90"
    }
   ]
  },
  {
   "title": "调用者上传文件耗费时间：P50",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(appId, remoteCallerIP, le) (rate(aliyun_oss_putobject_time_cost_histogram_bucket{appId=~\"cdn-release-web-server\", remoteCallerIP=~\"$remoteCallerIP\", rtCode=~\"CODE_OSS_PUTOBJECT_SUCCESS\", instance=~\"$instance\"}[1m]))) > 0",
     "legendFormat": "调用者上传文件耗费时间：P50"
    }
   ]
  }
 ]
}